### ISSUE TITLE
amp-img within amp-user-notification won't show on page load

### ISSUE THREAD

**Issue by JonnyVaine** [ampproject/docs#1353]
I'm trying to add an icon into an amp-user-notification component. However, on page load, the amp-img doesn't show. If I scroll further down the page and refresh, the image loads. This also happens if I scroll down and then resize the screen.

Has anyone come across this before, and if so has a fix?

This is the code on load:

![image](https://user-images.githubusercontent.com/22519838/51313083-9c117980-1a44-11e9-94f9-bc8accae90cc.png)

**Comment by matthiasrohmer** [comment]
Thanks for participating, @JonnyVaine! Sadly that's not really the right spot to ask questions about the AMP HTML project. It would be great if you could repost your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/amp-html) and tag it with `amp-html` since this issue board is really there to track issues around the actual ampproject.org

If you feel your problem might a bug then please file an issue over in the `[ampproject/amphtml](https://github.com/ampproject/amphtml/issues)` repository.
