### ISSUE TITLE
blog.amp.dev has invalid header links

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#1799]
https://blog.amp.dev/2018/09/18/governance/

* click on documentation => 404

**Comment by swissspidy** [comment]
Thanks for flagging this. It has now been fixed.

This has the same root cause as #1713: we currently have to manually update the markup for the header by building templates from this repo and/or just copying over directly from the website.

It would be great to have an already built version of the header somewhere that we could just automatically include without having to manually update every time something changes.

**Comment by matthiasrohmer** [comment]
@swissspidy, sounds good! Would an HTML file somewhere on amp.dev including just a `<style>` node and the remaining header markup suit your needs?

**Comment by felixarntz** [comment]
@matthiasrohmer 
> Would an HTML file somewhere on amp.dev including just a <style> node and the required header markup suit your needs?

Something like that would be great! Here's what we need mostly:
1. One HTML file with all markup making up the header (first top-level `svg`, `header`, `label`, `input`, `nav` nodes)
2. One HTML file with all markup making up the footer (the top-level `footer` node)
