### ISSUE TITLE
Short URLs for AMP.dev

### ISSUE THREAD

**Issue by machal** [ampproject/docs#1860]
I'm writing book/e-book about AMP and thinking about shorter URLs for docs pages.

For example:

```
https://amp.dev/documentation/components/amp-pixel
```

Should be (or have redirected variant) similar to the following:

```
https://amp.dev/docs/c/amp-pixel
```

…or even better:

```
https://amp.dev/amp-pixel
```

The problem with long URLs is that they are hard to read and impossible to print. Shorter version (`amp.dev/docs/c/amp-pixel`) looks fine in the printed page.

Of course, I can use `bit.ly` or a similar service, but I think AMP docs should be more friendly by default. After moving to `amp.dev` it is better, but still a problem.

**Comment by sebastianbenz** [comment]
That's a great idea. We've just launched the option to explicitly define short links via go.amp.dev (configured [here](https://github.com/ampproject/docs/blob/future/platform/config/go-links.yaml). 

However, it'd be great to have something generic for compoent docs. For example: go.amp.dev/c/amp-pixel.

//cc @pbakaus for thoughts.

**Comment by sebastianbenz** [comment]
...and awesome that you're writing a book about AMP ⚡️⚡️⚡️

**Comment by pbakaus** [comment]
Indeed great to hear about your book!

`amp.dev/amp-*` is my favorite, should not have any naming conflicts with existing pages. But if we want to be safe, I'm OK with `amp.dev/c/amp-*` as well.

**Comment by fstanis** [comment]
To echo some thoughts from #2182: I think it's better to separate this from `go.amp.dev` and make a new subdomain, e.g. `component.amp.dev/amp-form` or `c.amp.dev/amp-form`.

That said, if this is infeasible on infrastructure side, `go.amp.dev` works, but it would be good to also have a scheme to go to the component example rather than the reference doc. Maybe `go.amp.dev/sample/amp-form`?

**Comment by machal** [comment]
@fstanis Thanks. For me (and my book), `go.amp.dev/c/amp-img` is better, because it is shorter and consistent with other `go.amp.dev` links.

I don't think links to samples of the components are needed. It is simple to navigate there from main component page.

**Comment by fstanis** [comment]
I think there are many cases where short-linking to a sample is very useful, e.g. [in this SO answer](https://stackoverflow.com/a/56178123/2676845) linking to the `amp-lightbox-gallery` sample directly was better than linking to the component, since the sample very clearly demonstrates the feature.

That said, assuming `go.amp.dev/c/...` works, I believe we can close this via #2182 when I get to implement it (likely this week).

**Comment by machal** [comment]
I'm not seeing any update on live docs site here. Links like https://go.amp.dev/c/amp-img doesn't work. Is is waiting in deploy qeue?

**Comment by tharders** [comment]
@machal Correct, the changes are not deployed yet.
Not sure, but I expect this to happen sometime this week.
