### ISSUE TITLE
Example features linking to 404 pages

### ISSUE THREAD

**Issue by JosephAndrewMacLean** [ampproject/docs#2095]
## Examples of AMP features are linked to 404 pages.

Please provide:

- Page link: <https://amp.dev/advanced/image_galleries_with_amp-carousel/>
- Example URLs are 404ing from [](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/control_layout.html?format=email)

## How do we reproduce the issue?

Please provide the steps to reproduce the issue:

1. Start on https://amp.dev/
2. Select the Amp Email under About Menu
3. Click on "Start Developing" button
4. Open Develop accordion submenu and select "Layout & media queries"
5. Click the URL in the Tip under the tip - "TIP – See our side-by-side live demos of amp-img: Live Demos on AMP By Example."

What browser are you using? Chrome
What O/S are you using? Mac OS

**Comment by matthiasrohmer** [comment]
@keevkeev, can you do another round of looking for ampbyexample.com references?

**Comment by keevkeev** [comment]
The issue is coming from linking to the `amp-img` component in examples/components when the format filter is set to `email` and since the `amp-img` component doesn't exist with this filter we get a 404. We could either set the link to something like `{{g.doc('/content/amp-dev/documentation/examples/documentation/amp-img.html', locale=doc.locale).url.path}}?format=websites` or add email to the support formats in the front-matter inside `amp-dev/documentation/examples/documentation/amp-img.html`. Which would you prefer   @sebastianbenz

**Comment by matthiasrohmer** [comment]
Thinking more about it this could also be an issue for other pages, couldn't it? Basically everywhere where format-filtered page links to a document without explicitly appending a format as the filter-mechanism would then automatically append the current format.

That for example linking from a document filtered for stories to a document that is only available for ads this would also fail.

**Comment by sebastianbenz** [comment]
Sounds like we have two problems:

1. Examples 404 if there's a query parameter => this shouldn't happen

=> we should fix this in the backend

2. Documentation links might be invalid if there are format conflicts

=> here we should use format specific links in the doc

**Comment by sebastianbenz** [comment]
@fstanis is looking into automatically translating all samples into all supported formats. This would solve this issue. Until then, we should manually fix the link.
