### ISSUE TITLE
Tools page: support logos and improve description handling

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#2234]
We need a flag in the template/data do define wether the image is a screenshot or logo (and update the margins accordingly). 

@pbakaus can you elaborate what you mean by description handling?

![](https://user-images.githubusercontent.com/43004/58677177-d4d52f80-830f-11e9-97ba-7bfe8b25cbf1.png)

See #2217 for more context.

@sebil can you take this on?

**Comment by pbakaus** [comment]
re: description handling: Right now the cards look pretty stupid without a description (imho). The email team has requested to not have descriptions in the email service provider cards (so they can be fairly compared), but in other sections further below, the descriptions add value. It would be nice to tweak the design so that certain cards look great with just a logo and title.

Also: The email team requested "Email service providers" as overall category, as opposed to slotting these into "Creation tools". @sebil feel free to take a stab at this as well, I think it might also then be a good time to move the filtering to server-side, so that we can link to pre-filtered pages.

Thanks!

**Comment by sebil** [comment]
WIP
