### ISSUE TITLE
[samples] amp-addthis inline preview broken

### ISSUE THREAD

**Issue by sebastianbenz** [ampproject/docs#2241]
<img width="1117" alt="Screen Shot 2019-06-03 at 19 51 55" src="https://user-images.githubusercontent.com/380472/58823030-111ecd80-8639-11e9-89fb-827378eb0c57.png">

https://amp.dev/documentation/examples/components/amp-addthis/

**Comment by lluerich** [comment]
It won't do fixing the positioning, because it looks different on other browsers (e.g. Firefox and Safari).
I would suggest showing the component as intended (see screenshot).

![amp-addthis](https://user-images.githubusercontent.com/15678151/58958001-2c591c80-87a2-11e9-8419-7f1a1903284a.png)

The copy should be changed then, so that it contains a hint that the floating component can be found on the left.

**Comment by sebastianbenz** [comment]
Sounds perfect!

>
