### ISSUE TITLE
Sitemaps are not getting build when routes are filtered

### ISSUE THREAD

**Issue by matthiasrohmer** [ampproject/docs#2327]

**Comment by tharders** [comment]
We use a locale filter in the travis build, to be able to split the build on different machines.
The problem is, that the whitelist filter used to filter for the locale will only build the locale files and no sitemap.
We will switch to a blacklist filter.
After that the sitemap is build together witch each locale, but that should cause no big performance issue. Otherwise it might be possible to add an extra step where all locales are in the blacklist, so that only the sitemap will be generated in this step.
