### ISSUE TITLE
Add new batch of localized files

### ISSUE THREAD

**Issue by pbakaus** [ampproject/docs#2334]
We've received new translated markdown files from our Google internal localization vendor! I believe they've been translated when they still where on ampproject.org, so there's a little bit of migration work ahead.

Zip file with localized files: [Click here](https://drive.google.com/open?id=1U_53Yj7_OsbAfAUBobYfqh_2EokKARYP)

In the complicated vendor conversion process, the codeblocks got essentially URL encoded, like this one:

![image](https://user-images.githubusercontent.com/43004/59646311-493f0980-912b-11e9-9fc5-7d069e234128.png)

turned into this:

![image](https://user-images.githubusercontent.com/43004/59646320-56f48f00-912b-11e9-9c41-fb75f3b38886.png)

That still has to be converted back, I believe.

**Comment by pbakaus** [comment]
@matthiasrohmer please assign the right person, and let me know if there are any questions! Thanks

**Comment by dlemm** [comment]
I am on this. No questions so far. But unfortunately the vendor conversion process crashed some other things, too. Not just the codeblocks. So for example the lists and the inline code-snippets are broken as well.

**Comment by KevinACheek** [comment]
Could you send me a detailed list of the problems with the files you found? Thanks!

**Comment by dlemm** [comment]
Sure. So far I managed to implement all Arabic mds. So I concentrate on them. (I just have started now to do it by component. So I might add a few things for the other languages very soon.)
And here for better understanding, I will show pictures from amp-mustache.md file. I think it was the most broken one. I hope this is helpful. As soon as I find other problems in other languages I comment them here, too. 

Problems with HTML and <>-formatting:
As mentioned above the code-blocks in "``` ```" lose all their formatting. In addition, the brackets are transformed into entities. But not only in the three backticks, but they also do so in one backtick as well. So almost all brackets (in the first table they seem to work out) have to be changed manually to < and >. As it can be seen in the picture even in comments the brackets become entities.

![image](https://user-images.githubusercontent.com/28383171/59797269-9c59bd80-92df-11e9-9565-9764f54c4670.png)

![image](https://user-images.githubusercontent.com/28383171/59797277-a1b70800-92df-11e9-807f-4a3731baccd2.png)

![image](https://user-images.githubusercontent.com/28383171/59797285-a8de1600-92df-11e9-9ba8-428f7f0ef95a.png)


The code formatting of inline code is changing as well. Especially in the lists the one backticks do not work and have to be changed to <code></code>.

In order to display the list-format, there has to be an empty line in front of the list items.

Some sorted lists were beginning with just the numbers or numbers and - instead of "1." "2." "3." So there were no . and just the numbers. Therefore the list was not rendered as a list.

![image](https://user-images.githubusercontent.com/28383171/59797358-c7dca800-92df-11e9-8ca4-fcff2e8bc8d9.png)


In the amp-mustache-component the {{% raw %}} {{% endraw %}} were missing. Therefore the document couldn't be rendered and an error occurred.

![image](https://user-images.githubusercontent.com/28383171/59797376-d0cd7980-92df-11e9-97a8-0e86cd8ecff4.png)

Another problem is the transformation of the tips. The format on the site is ```[tip type="XYZ"] ... [/tip]```. In the translated versions the code is ```{% call callout('ملاحظة', type='note') %}...{% endcall %}``` The site is broken and cannot be rendered.

![image](https://user-images.githubusercontent.com/28383171/59797394-db880e80-92df-11e9-81ea-b7458bd0f179.png)

**Comment by KevinACheek** [comment]
I'm trying to use some scripts to apply fixes across all the files. Are there any that are completely unbroken, and I shouldn't fix?

**Comment by dlemm** [comment]
Not as far as I have checked. Sorry.

**Comment by KevinACheek** [comment]
Cool, I'll try to hunt through and fix the problems you pointed out. Some, like the Arabic text, can be applied only to specific files, others I can apply broadly across all 275. For example, I just fixed all the internal anchor links and the numbered lists that were missing a period immediately after the number.

**Comment by dlemm** [comment]
I am done with the Arabic files already. So I think for now they could be left out. If that is helping?

**Comment by KevinACheek** [comment]
Yes, that does help. Thanks!

question on the {% call callout ... {% endcall %} format. I copied that directly from the source. For example: https://raw.githubusercontent.com/ampproject/amphtml/master/extensions/amp-list/amp-list.md which renders as: https://amp.dev/documentation/components/amp-list?format=websites 

Should I replace them with [tip type="XYZ"] ... [/tip] ?

**Comment by dlemm** [comment]
That would help, yes. (just to be sure, instead of "xyz", there are "success", "note", "read-on" and "important" (instead of caution) similar to the callout types)

**Comment by pbakaus** [comment]
Re: tip format: This was due to Kevin having to work with the former files on ampproject.orf (master branch), and since then, the syntax for tips have changed. Not really anyones fault, a leftover of the migration.

**Comment by KevinACheek** [comment]
Hi, I fixed the tip types, fixed the {% raw %}/{% endraw% }, fixed the lists, fixed the internal anchor links, and started to fix the &lt; &gt;, however that script still needs some work.
Note: the raw source for the files still uses a lot of &lt; &gt;, specifically as "<code>&lt;..." and "...&gt;</code>".
for example here: https://raw.githubusercontent.com/ampproject/amphtml/master/extensions/amp-bind/amp-bind.md 
which renders here: https://amp.dev/documentation/components/amp-bind?format=websites

**Comment by KevinACheek** [comment]
I'm attaching the files at the point where I stopped for the evening. I'll finish up fixing them in the morning. 
[drive-download-20190620T004724Z-001.zip](https://github.com/ampproject/docs/files/3308360/drive-download-20190620T004724Z-001.zip)

**Comment by dlemm** [comment]
Re:re: tip format. I am sorry if I have blamed anyone. That was not my intention. Thanks for the files Kevin.

**Comment by KevinACheek** [comment]
Hi, quick update: 
1. Since you said you fixed all the Arabic files, I removed them from the list I'm fixing.
2. I fixed all the &lt; / &gt; instances, but have a question: 
 - - The source docs have "<code>&lt" and "&gt;</code>" everywhere a tag is next to a code tag. for example: https://raw.githubusercontent.com/ampproject/amphtml/master/extensions/amp-bind/amp-bind.md (https://amp.dev/documentation/components/amp-bind?format=websites ). Should I keep these in the final docs, or convert those instances to < and >?
3. I found a few places where the opening back-ticks for code blocks have been replaced with a single back tick. I'll search for that pattern and fix all of those.
4. I want to fix all the indents for the  code blocks and tables before I give the files back to you again. 
I'll send you another batch of the files a few hours later today, perhaps about 6:30 MDT.

**Comment by KevinACheek** [comment]
whoops, it formatted my answer as MD.
 - The source docs have `&lt` and `&gt` everywhere a tag is within and adjacent to a code tag. for example: 
```
   <tr>
     <td><code>&lt;amp-lightbox&gt;</code></td>
     <td><code>[open]</code><sup>*</sup></td>
     <td>
        Toggles display of the lightbox. Tip: Use <code>on="lightboxClose: AMP.setState(...)"</code> to update variables when the lightbox is closed.
     </td>
   </tr>
```

**Comment by dlemm** [comment]
Hey, thanks for the update. 
Please do convert them as well, because they are rendered as entities, too. 
I'm going to work on the files on Friday. It's 9:30 pm already.

**Comment by KevinACheek** [comment]
I replaced those as well. Thanks!

**Comment by KevinACheek** [comment]
Not everything is fixed yet. Here's a snapshot.
[drive-download-20190621T165711Z-001.zip](https://github.com/ampproject/docs/files/3315388/drive-download-20190621T165711Z-001.zip)

**Comment by dlemm** [comment]
Thanks @KevinACheek

**Comment by KevinACheek** [comment]
I think this ought to be the last of them (attached).
[AMP-reference-md-files.zip](https://github.com/ampproject/docs/files/3328187/AMP-reference-md-files.zip)

**Comment by dlemm** [comment]
Hey, thanks @KevinACheek I have spotted one more thing. Sorry. It looks like the ko-files do not have a teaser. I am not sure about that but behind ```티저:``` there is no text and the ```---``` are missing after the head as well.

**Comment by pbakaus** [comment]
Checking in - how far are we from landing these? Thanks!

**Comment by dlemm** [comment]
We should be finished by tomorrow.
