### ISSUE TITLE
Add former ampproject.org 404 Tic-Tac-Toe as sample

### ISSUE THREAD

**Issue by morsssss** [ampproject/docs#2338]
Not long ago, the esteemed @garanj made a lovely tic-tac-toe game with AMP. This found a home on ampproject.org as a feature on the 404 page.

Now we have a different 404 page. So tic-tac-toe is gone!

Can we bring back tic-tac-toe as a demo or a sample?

**Comment by matthiasrohmer** [comment]
That's right, it was kind of a nice showcase for `amp-bind`. I'd vote for it to come back as a feature sample.

**Comment by morsssss** [comment]
I was thinking the same thing. A sample!

**Comment by garanj** [comment]
Should be much easier nowadays since the operand limit has been raised from 50. And there are probably other new things in AMP that I'm not aware of.
The workings for the design for the 50 operand limit [are here](http://plemont.github.io/amp/2017/11/12/put-amp-in-the-centre-square.html) FWIW. Hope this helps.

**Comment by lluerich** [comment]
Merged in #2383
