### ISSUE TITLE
Main page's CSS is too long - fails AMP Validation

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#468]
On the main page - https://www.ampproject.org/, the page fails AMP Validation with the following error: **The author stylesheet specified in tag 'style amp-custom' is too long - we saw 53675 bytes whereas the limit is 50000 bytes.**

We need to trim our CSS.

**Comment by pbakaus** [comment]
Taking a look now.

**Comment by pbakaus** [comment]
Dramatically reduced CSS through various means (removing dead code, eliminating very old browser prefixes, etc). Went from 53kb to 35kb. Hopefully gives us some breathing room..

**Comment by axcelleria** [comment]
Can you create a function to split <style custom-amp> to several style when characters length close to 45k ?
<style custom-amp-0></style>
<style custom-amp-1></style>
...
<style custom-amp-last></style>

I stuck on this problem even no prefix prop added to internal CSS, Well the cause is page builder but if I disable the plugin on AMP it is really hard to create custom AMP CSS match design because HTML structure changed alot (simplified)

**Comment by acekingsx1** [comment]
Hello I am having the same issue on https://pclicious.net/download-twitter-for-desktop/. Can you please help me
