### ISSUE TITLE
amp-img with layout responsive not visible

### ISSUE THREAD

**Issue by 88kbbq** [ampproject/docs#5]
Using the Skeleton grid (http://getskeleton.com/) in my amp-html demo, I've set amp-img to layout=responsive because the images aspect ratio was being distorted on resize. With layout=responsive, this img width and height are changes to 0 and the image is not visible. Demo at pos.88k.com.tw (up temporarily)

**Comment by dvoytenko** [comment]
@88kbbq I took a look at your page. It uses a number of images. I assume the issue with the "hero" section? If so - the images there are defined using `position:absolute`. The issue here is that the images are defined without width, which in the initial layout means that they have the width equal 0. This is one thing that AMP enforces - downloading of images should not change the initial layout. You'd need to specify width here, e.g. `.phone {width: 80%}` or any other valid value. The `layout=responsive` will use this width as the available width and should be able to calculate aspect ratio correctly.

**Comment by dvoytenko** [comment]
Closing, but please reopen if needed.

**Comment by 88kbbq** [comment]
In a different time zone, sorry for delay in responding. So my HTML looks like this: <amp-img layout="responsive" class="phone" src="//getskeleton.com/examples/landing/images/iphone.png" width="300" height="615"></amp-img> 
What did you mean by width not being defined? How should I define width and height in this case?

**Comment by 88kbbq** [comment]
`<amp-img layout="responsive" class="phone" src="//getskeleton.com/examples/landing/images/iphone.png" width="300" height="615"></amp-img>`

**Comment by dvoytenko** [comment]
If you'd like to use `position:absolute` in CSS, then you also have to specify width on that element, otherwise by default it has width of 0. So, in your case you'd have to do:
```
.phone {
  /* these you already have */
  position: absolute;
  top: 0;
  left: 0;
  max-width: 80%;
  /* add */
  width: 100%;
}
```

Or, you can switch away from using `position:absolute`. That's just a constraint when using absolute positioning and floats.
