### ISSUE TITLE
Clarify intent and impact of amp-ad#data-loading-strategy

### ISSUE THREAD

**Issue by ithinkihaveacat** [ampproject/docs#667]
**Page link:**

https://www.ampproject.org/docs/reference/components/amp-ad#data-loading-strategy-(optional)

**Description of the documentation issue:**

Upon initial reading, the first two sentences appear to contradict each other:

> Instructs the ad to start loading when it is within the given number of viewports away (specified as a float value in the range of [0, 3]) from the current viewport.

From this, my understanding is that the larger the value, the earlier AMP will load the ad.

> Use a smaller value to gain higher degree of viewability, with the risk of generating fewer views.

But, smaller values increase the chance (i.e. higher viewability) the ad will be seen?

I think this apparently contradiction is due to my misunderstanding of what "viewability" means, but perhaps it would be useful to clarify what it means in this context.

/cc @andreban

**Comment by bpaduch** [comment]
Perhaps this might help:

Instructs the ad to start loading when it is within the given number of viewports away (specified as a float value in the range of [0, 3]) from the current viewport. Use a smaller value to gain higher degree of viewability (**i.e, the visible of the ad on the user's screen**), with the risk of generating fewer views (**i.e., the user views the ad**). If the attribute is not used, the default value is 3. If the attribute is used but the value is left blank, then a float value is assigned by the system, which optimizes for viewability without drastically impacting the views.

to: @jasti - is the correct clarification?  I'm assuming is visibility of the ad on the screen vs. impressions?

**Comment by jasti** [comment]
@bpaduch What we refer to here as viewability, is actually viewability rate. i.e. viewability rate = viewed impressions/ all impressions. 
Therefore, if the value is smaller, smaller the denominator, therefore, higher the viewability rate. However, a larger value would lead to higher impressions (because more number of ads are loaded) driving down the viewability rate. Does that help?

**Comment by bpaduch** [comment]
@jasti 

Okay, so to confirm:

1. A larger value indicates more impressions but a lower viewability.
2. A smaller value indicates fewer impressions but a higher viewability rate.

For example, if I specify 3, then ads from the current viewport to viewport 3 will load, which can equate to more ads loading. If I specify 1, then ads from the current and next viewport will load, so that can equate to fewer ads loading.

Here's the description revised - okay?:

Instructs the ad to start loading when the ad is within the given number of viewports away from the current viewport. You must specify a float value in the range of [0, 3].  By default, the value is 3. Use a smaller value to gain a higher degree of viewability **(i.e., a higher viewability rate) but with the risk of generating fewer impressions (i.e., fewer ads loaded).** If the attribute is used but the value is left blank, then a float value is assigned by the system, which optimizes for viewability without drastically impacting the **impressions**.

**Comment by ithinkihaveacat** [comment]
Much of my confusion was due to the fact that "viewability" is simply viewed_impressions/loaded_impressions, and so viewability goes down if more ads are (pre-)loaded, even if users see exactly the same number of ads. (I though—by analogy to "approachability"—that 
"high viewability" meant that users had a greater chance of seeing all the ads the publisher intended them to see, and that "low viewability" meant that users might miss ads.)

Perhaps the parenthetic clarification after "higher degree of viewability" could be **i.e. increase the chance that an ad, one loaded, will be seen**.

**Comment by jasti** [comment]
SGTM.
