### ISSUE TITLE
Automate how components are imported in

### ISSUE THREAD

**Issue by bpaduch** [ampproject/docs#756]
*leftover from Oct 2017 Fixit*

Currently adding components to docs is a manual process:
1) add the component to the [JSON file](https://github.com/ampproject/docs/blob/master/scripts/component_categories.json). 
2) Add the component to main [components page](https://github.com/ampproject/docs/blob/master/content/docs/reference/components.md).

To achieve this:
- Would need metadata in amphtml repo for reference docs: category + whether experimental, "in development", stable
- Would need to investigate "experimental" status; headless chrome test

Note: @sebastianbenz  has been looking into this as well. According to Sebastian: "The best bet is to use the validator protobuf definitions. This would enable many other features such as code completion in IDEs, syntax highlighting,..."

**Comment by johnw123** [comment]
If you’re looking for <a href="https://www.etech7.com/managed-it-services-in-nyc">Managed IT Services in NYC</a>, Etech7 is the right place for you. I’m a dummy in IT sphere, so all the time I need a good company to solve my IT problems. Finally I’ve found Etech7 and  when I need <a href="https://www.etech7.com/it-consulting">IT Consulting</a>, I’ll definitely call them.

**Comment by pbakaus** [comment]
@matthiasrohmer this is something we discussed previously, just wanted to make sure that during the reference doc conversion, we're adding the category as well, so we can fix this issue and do the categorization automatically without the JSON file.

**Comment by matthiasrohmer** [comment]
Hm, so the categorization is currently still implemented using the JSON file. I've added the format tagging via the same technique because I thought we wanted to have the documents in the `amphtml` repository as loosely coupled as possible. But I would also like to maintain the category directly there and as Sebastian suggested use the protobuf files to determine for which format a component is valid.

Another meta information that is currently autogenerated via RegExes for amp.dev are the description texts.

*Lange Rede kurzer Sinn*: shall we move all of this into the frontmatter of the documents inside `amphtml`?

**Comment by matthiasrohmer** [comment]
Metadata has been added to the components in ampproject/amphtml itself.
