### ISSUE TITLE
Gap between sidebar and navbar

### ISSUE THREAD

**Issue by omi10859** [ampproject/docs#791]
When we scroll down the page. Navbar with "class id =doc-sidebar" Which should be absolute `position=absolute;` keep fixed. This problem is with all pages of docs and Nav Bar.
![issue](https://user-images.githubusercontent.com/26123416/34317807-b1a51bb2-e7dc-11e7-933e-b742571b7a2e.png)

**Comment by omi10859** [comment]
Should I fix this..

**Comment by bpaduch** [comment]
If you'd like, that'd be great.  Please make sure to test it locally before submitting a PR.

**Comment by bpaduch** [comment]
Turns out we can't make it `absolute` because then when you try to scroll the doc, the sidenav moves as well; we want the doc nav to have separate fixed navigation.

@pbakaus - possibly we can remove [this CSS](https://github.com/ampproject/docs/blame/master/assets/sass/_promo.scss#L80).  The promo won't be the whole width but at least we won't have that unpleasant gap when a user scrolls.

**Comment by matthiasrohmer** [comment]
Not current on amp.dev anymore.
