### ISSUE TITLE
cdn.ampproject.org/v0.js requirement?

### ISSUE THREAD

**Issue by yieme** [ampproject/docs#9]
According to https://www.ampproject.org/docs/get_started/create/basic_markup.html a requirement to being AMP compliant is to include `<script async src="https://cdn.ampproject.org/v0.js"></script>` right before the `</head>` tag. Could not the AMP JS code be served via a CDN like Akamai other than `cdn.ampproject.org` which might improve availability to clients? If a site could host the AMP JS with their other CDN content then CORS setup could would seem remain intact. If Google should rank pages based upon AMP compliance, this would seem to tie page ranking to another Google product, that being `cdn.ampproject.org` which, as I understand it, is served via Google's CDN.

Is this an ease of implementation detail? Saying the script tag right before `</head>` must be literally `https://cdn.ampproject.org/v0.js`? If so, then what about `v1.js`? Or is the test a regular expression? Could it not be that the script tag right before `</head>` somehow otherwise indicate that it is AMP JS by say the `src` attribute containing `ampproject` or there being an `amp` attribute included, ex  `<script async amp src="https://cdn.somedomain.com/v0.js"></script>`

Requiring AMP JS code before `</head>` make sense and having it available via `cdn.ampproject.org` is great. However, forcing the use of a specific seems counter to an open web. Thoughts?

**Comment by cramforce** [comment]
@yieme Thanks for the question!

First of all: The check for `v0.js` is, indeed, a regex and allows future version increments. The version will only be incremented for changes that would otherwise breaks (a subset of) existing documents.

There are a few reasons for mandating 1 specific URL VS. allowing it to be served from other locations:

- AMP documents are designed to be serveable from cache servers. These need a way to understand the AMP version that the documents are compatible with. For that it is important that the doc is explicit about it and the only way to be sure is to have everyone on the actual same JS file.
- We do not want a large "version diversity" (mostly because of the above; and because it would be bad for cacheability of the JS files). Instead almost all documents should use the same version of AMP. If everyone was hosting their own file, they would quickly develop dependencies on specific versions.
- This makes it very likely that the JS files are served from cache.

One thing of note: Akamai could make their own AMP cache CDN and for documents served from this, they could rewrite the JS URLs to go to their own server (maybe they shouldn't for cache reasons, but they could).

https://github.com/ampproject/amphtml/pull/998 was submitted to improve the failure case when the primary CDN is down. On top of this, we will soon add a ServiceWorker that for people who have ever been to an AMP document ensures that they can always serve the AMP JS files without speaking to a server which will further improve reliability.

**Comment by yieme** [comment]
@cramforce thank you for your clarification.

Would not `ampcdn.hostdomain.com/v?.js` being a CDN cache proxy of `cdn.ampproject.org/v?.js`also accomplish the objectives you outlined and also address the concerns raised? Perhaps I'm missing. Thoughts?

**Comment by cramforce** [comment]
We could consider to add a small number of other hosts that are trusted to serve identical versions of the AMP scripts and are part of the official deployment process.

I'm not sure what the real benefit would be as each page would need to chose between N hosts, but they all in itself could go down, so there is no redundancy. On the other hand it would be bad for users, because cache hit rates would go down, and it would complicate the roll out process for developers. E.g. we're rolling out a Chrome-style dev channel of the AMP files and that working relies on a cookie on the single JS origin.

**Comment by do4** [comment]
A proxy cache could retain the last version if upstream was lost, so I don't see it as if one fails they all fail. but the opposite, you have redundancy and hence a fail over. The single origin cookie does seem a problem though. Thank you, Malte
