### ISSUE TITLE
Can anyone tell me how to do redirect from domain to AMP page ?

### ISSUE THREAD

**Issue by Anbarasan-321** [ampproject/docs#900]
For example I have actual domain “www.examble.com” and its AMP project is www.examble.com/amp

I want to know how to redirect from actual domain to AMP project automatically.
I am using Core PHP.

**Comment by cara-tm** [comment]
You don't need special things. Here is how to: https://www.ampproject.org/docs/fundamentals/discovery

**Comment by bpaduch** [comment]
For support questions, I recommend that you use [Stack Overflow](http://stackoverflow.com/questions/tagged/amp-html) to find answers to questions about AMP; since members of the AMP Project community regularly monitor Stack Overflow you will probably receive the fastest response to your questions there.
