### ISSUE TITLE
Add microdata metadata examples in addition to JSON-LD

### ISSUE THREAD

**Issue by tomremo** [ampproject/docs#95]
Our [Rich Snippets documents](https://developers.google.com/structured-data/rich-snippets/articles#article_markup_properties) have both JSON-LD and microdata examples, but ampproject.org [does not](https://www.ampproject.org/docs/guides/discovery.html).

@Meggin

**Comment by bpaduch** [comment]
There are other types of examples in the linked text on that doc - "More examples can be found in the [ampproject examples folder,](https://github.com/ampproject/amphtml/tree/master/examples/metadata-examples) including the alternative HTML attribute syntax)." Including microdata examples.

I think this is suitable and I'll close this bug.  If you feel otherwise, please advise and reopen this bug. Thanks.
